import { modKey } from './util'
export const HOTKEYS: { label: string; keys: string[]; id?: string }[] = [
  { id: 'palette', label: 'Палитра команд', keys: [modKey, 'K'] },
  { id: 'files', label: 'Найти файл', keys: [modKey, 'P'] },
  { id: 'goto', label: 'Перейти к строке', keys: [modKey, 'G'] },
  { id: 'today', label: 'Сегодня', keys: [modKey, 'Shift', 'Y'] },
  { id: 'replace', label: 'Найти и заменить в проекте', keys: [modKey, 'Shift', 'H'] },
  { id: 'git', label: 'Панель Git', keys: [modKey, 'Shift', 'G'] },
  { id: 'search', label: 'Поиск по содержимому', keys: [modKey, 'Shift', 'F'] },
  { id: 'newchat', label: 'Новый чат', keys: [modKey, 'Shift', 'A'] },
  { id: 'newtask', label: 'Новая задача', keys: [modKey, 'Shift', 'T'] },
  { id: 'term', label: 'Терминал', keys: [modKey, '`'] },
  { id: 'dock', label: 'Нижняя панель', keys: [modKey, 'J'] },
  { id: 'pipeline', label: 'Запустить пайплайн', keys: [modKey, 'Shift', 'R'] },
  { id: 'project', label: 'Сменить проект', keys: [modKey, 'O'] },
  { id: 'side', label: 'Показать / скрыть сайдбар', keys: [modKey, 'B'] },
  { id: 'settings', label: 'Настройки', keys: [modKey, ','] },
  { id: 'design', label: 'Режим дизайна', keys: [modKey, 'Shift', 'D'] },
  { id: 'shortcuts', label: 'Горячие клавиши', keys: [modKey, '/'] },
  { label: 'Редактор: сохранить', keys: [modKey, 'S'] },
  { label: 'Редактор: закомментировать строки', keys: [modKey, '/'] },
  { label: 'Редактор: отступ / обратный отступ', keys: ['Tab', 'Shift', 'Tab'] },
  { label: 'Закрыть вкладку файла', keys: [modKey, 'W'] },
  { label: 'Поиск в чате', keys: [modKey, 'F'] },
  { label: 'Терминал: размер шрифта', keys: [modKey, '+ / − / 0'] },
  { label: 'Соседняя вкладка файла', keys: ['Alt', '← / →'] },
  { label: 'Остановить агента', keys: ['Esc'] },
]
